# Generated by Django 2.0 on 2018-01-30 15:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPlanned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateField(blank=True)),
                ('date_achieved', models.DateField(blank=True)),
                ('nb_planned', models.IntegerField(blank=True)),
                ('nb_achieved', models.IntegerField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestProjectExplorerApp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='GanttTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(default='OUTPUT', max_length=10)),
                ('category', models.CharField(default='DONORS', max_length=10)),
                ('unit', models.CharField(default='Number', max_length=10)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_code', models.IntegerField(blank=True, null=True)),
                ('grant_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('organisations', models.CharField(blank=True, max_length=255, null=True)),
                ('territory', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('main_subject', models.CharField(max_length=255)),
                ('total_budget', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_on_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestProjectExplorerApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='BestProjectExplorerApp.Project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='BestProjectExplorerApp.Output'),
        ),
    ]
