# Generated by Django 2.0 on 2018-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestProjectExplorerApp', '0003_auto_20180130_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='monthly_report',
            field=models.CharField(blank=True, default='0,0,0,0,0,0,0,0,0,0,0,0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='best_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
